name: libmidi
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'examples/**'
      - '.github/workflows/teensy.yml'
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -Wno-dev

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --target teensy_x86_midi_stubs --config $BUILD_TYPE